version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-104-136.compute-1.amazonaws.com
            database: d2a204ki3tkh81
            schema: public
            user: vddpzbcpmmdoiy
            password: 47beee2792e9ed4635e8f4958eb2a0b4070490e628638c9cbdec6959fb138393
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
